# Generated by Django 5.1.3 on 2024-11-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPaid',
            new_name='totalPrice',
        ),
    ]
